---------Built in functions in string-------------

--1)ASCII

select ASCII('a') as lowercase,ASCII('A') as uppercase --output in int-97,65

--2)CHAR

SELECT CHAR(65) AS CHARACTER -- IT CONVERTS ASCII CODE INTO REPRESENTING CHARACTER

DECLARE @START INT
SET @START=65
WHILE(@START <=90)
BEGIN
	PRINT CHAR(@START)
	SET @START=@START+1
END

---3)LTRIM
SELECT LTRIM('    HELLO') AS TRIMMED -- IT IS USED TO REMOVE WHITE SPACES ON THE LEFT SIDE

---4)RTRIM
SELECT RTRIM('HELLO       ') AS TRM -- IT IS USED TO REMOVE WHITE SPACES ON THE RIGHT SIDE

----5)LOWER CONVERT INTO SMALLER LETTER
SELECT LOWER('SHANKAR') AS NAME

----6)UPPER
SELECT UPPER('shankar') AS N

----7)LEN
SELECT LEN('SHANKAR') AS LENGTH

---8)REVERSE
SELECT REVERSE('MADAM') A

---9)LEFT
Select LEFT('ABCDE', 3) --ABC OUTPUT IT STARTS FROM LEFT SIDE AND TAKES CHAR UPTO MENTION VALUE HERE 3 SO ABC

---10)RIGHT
Select RIGHT('ABCDE', 3) --HERE IT STARTS FROM RIGHT

----11)CHARINDEX(‘Expression_To_Find’, ‘Expression_To_Search’, ‘Start_Location’)
SELECT CHARINDEX('S','   SHANKAR')AS INDEXPOSITION


---12)SUBSTRING()
Select SUBSTRING('info@dotnettutorials.net',(CHARINDEX('@', 'info@dotnettutorials.net') + 1),

(LEN('info@dotnettutorials.net') ))

---13)SPACE()
SELECT UPPER('SHANKAR')+SPACE(5)+LOWER('SHANMAUGAM')


----14)REPLICATE()
SELECT REPLICATE('*',5) --REPEAT THE CHARACTER NO OF TIMES HERE IT WILL REPEAT 5

-----15)REPLACE() PARAMETER -EXPRESSION LIKE NAME,EMAIL,2)PATTERN MATCHING 3) REPLACED STRING
SELECT REPLACE('SHANKAR89479@GMAIL.COM','89479','2002') 

